packages:
  - packages/*
  - playground/**
  - '!playground/bun'
catalog:
  typescript: ^5.9.3
  zod: ^4.1.13
  deno: ^2.5.6
  jsr: ^0.13.5
  jsr-exports-lint: ^0.4.1
  publint: ^0.3.16
  tsdown: 0.15.12
  '@types/node': ^24.10.2
  typedoc: ^0.28.15
  tsx: ^4.21.0
  typedoc-plugin-markdown: ^4.9.0
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - deno
  - knip
  - publint
  - tsx
  - '@bomb.sh/tab'
  - eslint-plugin-jsdoc
  - '@typescript/native-preview'
  - lint-staged
  - tsdown
  - rolldown
  - '@rolldown/pluginutils'
  - '@kazupon/eslint-config'
  - gunshi
  - '@gunshi/bone'
  - '@gunshi/docs'
  - '@gunshi/definition'
  - '@gunshi/plugin'
  - '@gunshi/plugin-completion'
  - '@gunshi/plugin-dryrun'
  - '@gunshi/plugin-global'
  - '@gunshi/plugin-i18n'
  - '@gunshi/plugin-renderer'
  - '@gunshi/resources'
  - '@gunshi/shared'
