packages:
  - packages/*
  - playground/**
  - '!playground/bun'
catalog:
  typescript: ^5.9.3
  zod: ^4.1.12
  deno: ^2.5.4
  jsr: ^0.13.5
  jsr-exports-lint: ^0.4.1
  publint: ^0.3.14
  tsdown: ^0.15.6
  '@types/node': ^22.18.8
  typedoc: ^0.28.13
  typedoc-plugin-markdown: ^4.9.0
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - deno
  - tsx
  - '@bomb.sh/tab'
  - eslint-plugin-jsdoc
  - '@typescript/native-preview'
  - lint-staged
  - '@kazupon/eslint-config'
  - gunshi
  - '@gunshi/bone'
  - '@gunshi/definition'
  - '@gunshi/plugin'
  - '@gunshi/plugin-completion'
  - '@gunshi/plugin-dryrun'
  - '@gunshi/plugin-global'
  - '@gunshi/plugin-i18n'
  - '@gunshi/plugin-renderer'
  - '@gunshi/resources'
  - '@gunshi/shared'
