packages:
  - packages/*
  - playground/**
catalog:
  typescript: ^5.9.2
  zod: ^4.0.14
  deno: ^2.4.3
  jsr: ^0.13.5
  jsr-exports-lint: ^0.4.1
  publint: ^0.3.12
  tsdown: ^0.13.2
  '@types/node': ^22.17.0
  typedoc: ^0.28.9
  typedoc-plugin-markdown: ^4.8.0
