packages:
  - packages/*
  - playground/**
catalog:
  typescript: ^5.9.2
  zod: ^4.1.11
  deno: ^2.5.1
  jsr: ^0.13.5
  jsr-exports-lint: ^0.4.1
  publint: ^0.3.13
  tsdown: ^0.14.2
  '@types/node': ^22.18.6
  typedoc: ^0.28.13
  typedoc-plugin-markdown: ^4.9.0
