packages:
  - packages/*
  - playground/**
catalog:
  typescript: ^5.8.3
  zod: ^4.0.13
  deno: ^2.4.2
  jsr: ^0.13.5
  jsr-exports-lint: ^0.4.1
  publint: ^0.3.12
  tsdown: ^0.13.0
  '@types/node': ^22.16.5
  typedoc: ^0.28.8
  typedoc-plugin-markdown: ^4.7.1
