packages:
  - packages/*
  - playground/**
catalog:
  typescript: ^5.8.3
  zod: ^3.25.74
  deno: ^2.4.0
  jsr: ^0.13.5
  jsr-exports-lint: ^0.4.1
  publint: ^0.3.12
  tsdown: ^0.12.9
  '@types/node': ^22.16.0
  typedoc: ^0.28.7
  typedoc-plugin-markdown: ^4.7.0
