/**
 * Auto-generated API documentation navigation.
 * This file is automatically generated by the docs plugin.
 * Do not edit manually.
 */

export interface NavItem {
  title: string
  path: string
  children?: NavItem[]
}

export const apiOxNav: NavItem[] = [
  {
    title: 'Agent',
    path: '/api-ox/agent'
  },
  {
    title: 'Bone',
    path: '/api-ox/bone'
  },
  {
    title: 'Builtin',
    path: '/api-ox/builtin'
  },
  {
    title: 'Constants',
    path: '/api-ox/constants'
  },
  {
    title: 'Context',
    path: '/api-ox/context'
  },
  {
    title: 'Context',
    path: '/api-ox/context'
  },
  {
    title: 'Core',
    path: '/api-ox/core'
  },
  {
    title: 'Core',
    path: '/api-ox/core'
  },
  {
    title: 'Decorators',
    path: '/api-ox/decorators'
  },
  {
    title: 'Definition',
    path: '/api-ox/definition'
  },
  {
    title: 'Dependency',
    path: '/api-ox/dependency'
  },
  {
    title: 'Generator',
    path: '/api-ox/generator'
  },
  {
    title: 'Types',
    path: '/api-ox/types'
  },
  {
    title: 'Utils',
    path: '/api-ox/utils'
  }
] as const
