/**
 * Auto-generated API documentation navigation (VitePress sidebar shape).
 *
 * Generated by packages/docs/scripts/generate-api-with-ox-content.ts: ox-content
 * nav metadata, normalized to VitePress `{ text, link, items }` on the consumer
 * side (see .notes/029). Do not edit manually.
 */

export interface NavItem {
  text: string
  link?: string
  collapsed?: boolean
  items?: NavItem[]
}

export const apiOxNav: NavItem[] = [
  {
    text: 'Agent',
    link: '/api-ox/agent/',
    collapsed: true,
    items: [
      {
        text: 'Functions',
        collapsed: true,
        items: [
          {
            text: 'getAgentProfile',
            link: '/api-ox/agent/functions/getAgentProfile'
          }
        ]
      }
    ]
  },
  {
    text: 'Combinators',
    link: '/api-ox/combinators/',
    collapsed: true,
    items: [
      {
        text: 'Functions',
        collapsed: true,
        items: [
          {
            text: 'args',
            link: '/api-ox/combinators/functions/args'
          },
          {
            text: 'boolean',
            link: '/api-ox/combinators/functions/boolean'
          },
          {
            text: 'choice',
            link: '/api-ox/combinators/functions/choice'
          },
          {
            text: 'combinator',
            link: '/api-ox/combinators/functions/combinator'
          },
          {
            text: 'describe',
            link: '/api-ox/combinators/functions/describe'
          },
          {
            text: 'extend',
            link: '/api-ox/combinators/functions/extend'
          },
          {
            text: 'float',
            link: '/api-ox/combinators/functions/float'
          },
          {
            text: 'integer',
            link: '/api-ox/combinators/functions/integer'
          },
          {
            text: 'map',
            link: '/api-ox/combinators/functions/map'
          },
          {
            text: 'merge',
            link: '/api-ox/combinators/functions/merge'
          },
          {
            text: 'merge',
            link: '/api-ox/combinators/functions/merge'
          },
          {
            text: 'merge',
            link: '/api-ox/combinators/functions/merge'
          },
          {
            text: 'merge',
            link: '/api-ox/combinators/functions/merge'
          },
          {
            text: 'multiple',
            link: '/api-ox/combinators/functions/multiple'
          },
          {
            text: 'number',
            link: '/api-ox/combinators/functions/number'
          },
          {
            text: 'positional',
            link: '/api-ox/combinators/functions/positional'
          },
          {
            text: 'positional',
            link: '/api-ox/combinators/functions/positional'
          },
          {
            text: 'required',
            link: '/api-ox/combinators/functions/required'
          },
          {
            text: 'short',
            link: '/api-ox/combinators/functions/short'
          },
          {
            text: 'string',
            link: '/api-ox/combinators/functions/string'
          },
          {
            text: 'unrequired',
            link: '/api-ox/combinators/functions/unrequired'
          },
          {
            text: 'withDefault',
            link: '/api-ox/combinators/functions/withDefault'
          }
        ]
      },
      {
        text: 'Interfaces',
        collapsed: true,
        items: [
          {
            text: 'BaseOptions',
            link: '/api-ox/combinators/interfaces/BaseOptions'
          },
          {
            text: 'BooleanOptions',
            link: '/api-ox/combinators/interfaces/BooleanOptions'
          },
          {
            text: 'CombinatorOptions',
            link: '/api-ox/combinators/interfaces/CombinatorOptions'
          },
          {
            text: 'FloatOptions',
            link: '/api-ox/combinators/interfaces/FloatOptions'
          },
          {
            text: 'IntegerOptions',
            link: '/api-ox/combinators/interfaces/IntegerOptions'
          },
          {
            text: 'NumberOptions',
            link: '/api-ox/combinators/interfaces/NumberOptions'
          },
          {
            text: 'StringOptions',
            link: '/api-ox/combinators/interfaces/StringOptions'
          }
        ]
      },
      {
        text: 'Type Aliases',
        collapsed: true,
        items: [
          {
            text: 'Combinator',
            link: '/api-ox/combinators/type-aliases/Combinator'
          },
          {
            text: 'CombinatorSchema',
            link: '/api-ox/combinators/type-aliases/CombinatorSchema'
          }
        ]
      }
    ]
  },
  {
    text: 'Context',
    link: '/api-ox/context/',
    collapsed: true,
    items: [
      {
        text: 'Functions',
        collapsed: true,
        items: [
          {
            text: 'createCommandContext',
            link: '/api-ox/context/functions/createCommandContext'
          }
        ]
      },
      {
        text: 'Interfaces',
        collapsed: true,
        items: [
          {
            text: 'CommandContextParams',
            link: '/api-ox/context/interfaces/CommandContextParams'
          }
        ]
      }
    ]
  },
  {
    text: 'Default',
    link: '/api-ox/default/',
    collapsed: true,
    items: [
      {
        text: 'Functions',
        collapsed: true,
        items: [
          {
            text: 'parseArgs',
            link: '/api-ox/default/functions/parseArgs'
          },
          {
            text: 'resolveArgs',
            link: '/api-ox/default/functions/resolveArgs'
          },
          {
            text: 'cli',
            link: '/api-ox/default/functions/cli'
          },
          {
            text: 'cli',
            link: '/api-ox/default/functions/cli'
          },
          {
            text: 'cli',
            link: '/api-ox/default/functions/cli'
          },
          {
            text: 'cli',
            link: '/api-ox/default/functions/cli'
          },
          {
            text: 'cli',
            link: '/api-ox/default/functions/cli'
          },
          {
            text: 'cli',
            link: '/api-ox/default/functions/cli'
          },
          {
            text: 'createCommandContext',
            link: '/api-ox/default/functions/createCommandContext'
          },
          {
            text: 'define',
            link: '/api-ox/default/functions/define'
          },
          {
            text: 'define',
            link: '/api-ox/default/functions/define'
          },
          {
            text: 'defineWithTypes',
            link: '/api-ox/default/functions/defineWithTypes'
          },
          {
            text: 'lazy',
            link: '/api-ox/default/functions/lazy'
          },
          {
            text: 'lazy',
            link: '/api-ox/default/functions/lazy'
          },
          {
            text: 'lazy',
            link: '/api-ox/default/functions/lazy'
          },
          {
            text: 'lazyWithTypes',
            link: '/api-ox/default/functions/lazyWithTypes'
          },
          {
            text: 'plugin',
            link: '/api-ox/default/functions/plugin'
          },
          {
            text: 'plugin',
            link: '/api-ox/default/functions/plugin'
          },
          {
            text: 'plugin',
            link: '/api-ox/default/functions/plugin'
          }
        ]
      },
      {
        text: 'Classes',
        collapsed: true,
        items: [
          {
            text: 'DefaultTranslation',
            link: '/api-ox/default/classes/DefaultTranslation'
          }
        ]
      },
      {
        text: 'Interfaces',
        collapsed: true,
        items: [
          {
            text: 'CommandContextParams',
            link: '/api-ox/default/interfaces/CommandContextParams'
          },
          {
            text: 'PluginContext',
            link: '/api-ox/default/interfaces/PluginContext'
          },
          {
            text: 'PluginDependency',
            link: '/api-ox/default/interfaces/PluginDependency'
          },
          {
            text: 'PluginOptions',
            link: '/api-ox/default/interfaces/PluginOptions'
          },
          {
            text: 'PluginWithExtension',
            link: '/api-ox/default/interfaces/PluginWithExtension'
          },
          {
            text: 'PluginWithoutExtension',
            link: '/api-ox/default/interfaces/PluginWithoutExtension'
          },
          {
            text: 'Args',
            link: '/api-ox/default/interfaces/Args'
          },
          {
            text: 'ArgSchema',
            link: '/api-ox/default/interfaces/ArgSchema'
          },
          {
            text: 'ArgToken',
            link: '/api-ox/default/interfaces/ArgToken'
          },
          {
            text: 'GunshiParams',
            link: '/api-ox/default/interfaces/GunshiParams'
          },
          {
            text: 'CommandEnvironment',
            link: '/api-ox/default/interfaces/CommandEnvironment'
          },
          {
            text: 'CliOptions',
            link: '/api-ox/default/interfaces/CliOptions'
          },
          {
            text: 'CommandContext',
            link: '/api-ox/default/interfaces/CommandContext'
          },
          {
            text: 'CommandContextExtension',
            link: '/api-ox/default/interfaces/CommandContextExtension'
          },
          {
            text: 'RenderingOptions',
            link: '/api-ox/default/interfaces/RenderingOptions'
          },
          {
            text: 'Command',
            link: '/api-ox/default/interfaces/Command'
          },
          {
            text: 'SubCommandable',
            link: '/api-ox/default/interfaces/SubCommandable'
          }
        ]
      },
      {
        text: 'Type Aliases',
        collapsed: true,
        items: [
          {
            text: 'OnPluginExtension',
            link: '/api-ox/default/type-aliases/OnPluginExtension'
          },
          {
            text: 'Plugin',
            link: '/api-ox/default/type-aliases/Plugin'
          },
          {
            text: 'PluginExtension',
            link: '/api-ox/default/type-aliases/PluginExtension'
          },
          {
            text: 'PluginFunction',
            link: '/api-ox/default/type-aliases/PluginFunction'
          },
          {
            text: 'ArgValues',
            link: '/api-ox/default/type-aliases/ArgValues'
          },
          {
            text: 'Awaitable',
            link: '/api-ox/default/type-aliases/Awaitable'
          },
          {
            text: 'Prettify',
            link: '/api-ox/default/type-aliases/Prettify'
          },
          {
            text: 'ExtendContext',
            link: '/api-ox/default/type-aliases/ExtendContext'
          },
          {
            text: 'DefaultGunshiParams',
            link: '/api-ox/default/type-aliases/DefaultGunshiParams'
          },
          {
            text: 'GunshiParamsConstraint',
            link: '/api-ox/default/type-aliases/GunshiParamsConstraint'
          },
          {
            text: 'CommandCallMode',
            link: '/api-ox/default/type-aliases/CommandCallMode'
          },
          {
            text: 'CommandContextCore',
            link: '/api-ox/default/type-aliases/CommandContextCore'
          },
          {
            text: 'LazyCommand',
            link: '/api-ox/default/type-aliases/LazyCommand'
          },
          {
            text: 'Commandable',
            link: '/api-ox/default/type-aliases/Commandable'
          },
          {
            text: 'CommandExamplesFetcher',
            link: '/api-ox/default/type-aliases/CommandExamplesFetcher'
          },
          {
            text: 'CommandRunner',
            link: '/api-ox/default/type-aliases/CommandRunner'
          },
          {
            text: 'CommandLoader',
            link: '/api-ox/default/type-aliases/CommandLoader'
          },
          {
            text: 'CommandDecorator',
            link: '/api-ox/default/type-aliases/CommandDecorator'
          },
          {
            text: 'RendererDecorator',
            link: '/api-ox/default/type-aliases/RendererDecorator'
          },
          {
            text: 'ValidationErrorsDecorator',
            link: '/api-ox/default/type-aliases/ValidationErrorsDecorator'
          }
        ]
      },
      {
        text: 'Variables',
        collapsed: true,
        items: [
          {
            text: 'ANONYMOUS_COMMAND_NAME',
            link: '/api-ox/default/variables/ANONYMOUS_COMMAND_NAME'
          }
        ]
      }
    ]
  },
  {
    text: 'Definition',
    link: '/api-ox/definition/',
    collapsed: true,
    items: [
      {
        text: 'Functions',
        collapsed: true,
        items: [
          {
            text: 'createCommandContext',
            link: '/api-ox/definition/functions/createCommandContext'
          },
          {
            text: 'define',
            link: '/api-ox/definition/functions/define'
          },
          {
            text: 'define',
            link: '/api-ox/definition/functions/define'
          },
          {
            text: 'defineWithTypes',
            link: '/api-ox/definition/functions/defineWithTypes'
          },
          {
            text: 'lazy',
            link: '/api-ox/definition/functions/lazy'
          },
          {
            text: 'lazy',
            link: '/api-ox/definition/functions/lazy'
          },
          {
            text: 'lazy',
            link: '/api-ox/definition/functions/lazy'
          },
          {
            text: 'lazyWithTypes',
            link: '/api-ox/definition/functions/lazyWithTypes'
          }
        ]
      },
      {
        text: 'Interfaces',
        collapsed: true,
        items: [
          {
            text: 'Args',
            link: '/api-ox/definition/interfaces/Args'
          },
          {
            text: 'ArgSchema',
            link: '/api-ox/definition/interfaces/ArgSchema'
          },
          {
            text: 'Command',
            link: '/api-ox/definition/interfaces/Command'
          },
          {
            text: 'GunshiParams',
            link: '/api-ox/definition/interfaces/GunshiParams'
          },
          {
            text: 'CommandContextParams',
            link: '/api-ox/definition/interfaces/CommandContextParams'
          }
        ]
      },
      {
        text: 'Type Aliases',
        collapsed: true,
        items: [
          {
            text: 'ArgValues',
            link: '/api-ox/definition/type-aliases/ArgValues'
          },
          {
            text: 'CommandLoader',
            link: '/api-ox/definition/type-aliases/CommandLoader'
          },
          {
            text: 'CommandRunner',
            link: '/api-ox/definition/type-aliases/CommandRunner'
          },
          {
            text: 'DefaultGunshiParams',
            link: '/api-ox/definition/type-aliases/DefaultGunshiParams'
          },
          {
            text: 'ExtendContext',
            link: '/api-ox/definition/type-aliases/ExtendContext'
          },
          {
            text: 'LazyCommand',
            link: '/api-ox/definition/type-aliases/LazyCommand'
          }
        ]
      }
    ]
  },
  {
    text: 'Generator',
    link: '/api-ox/generator/',
    collapsed: true,
    items: [
      {
        text: 'Functions',
        collapsed: true,
        items: [
          {
            text: 'generate',
            link: '/api-ox/generator/functions/generate'
          }
        ]
      },
      {
        text: 'Type Aliases',
        collapsed: true,
        items: [
          {
            text: 'GenerateOptions',
            link: '/api-ox/generator/type-aliases/GenerateOptions'
          }
        ]
      }
    ]
  },
  {
    text: 'Plugin',
    link: '/api-ox/plugin/',
    collapsed: true,
    items: [
      {
        text: 'Functions',
        collapsed: true,
        items: [
          {
            text: 'createCommandContext',
            link: '/api-ox/plugin/functions/createCommandContext'
          },
          {
            text: 'plugin',
            link: '/api-ox/plugin/functions/plugin'
          },
          {
            text: 'plugin',
            link: '/api-ox/plugin/functions/plugin'
          },
          {
            text: 'plugin',
            link: '/api-ox/plugin/functions/plugin'
          }
        ]
      },
      {
        text: 'Interfaces',
        collapsed: true,
        items: [
          {
            text: 'CommandContextParams',
            link: '/api-ox/plugin/interfaces/CommandContextParams'
          },
          {
            text: 'PluginContext',
            link: '/api-ox/plugin/interfaces/PluginContext'
          },
          {
            text: 'PluginDependency',
            link: '/api-ox/plugin/interfaces/PluginDependency'
          },
          {
            text: 'PluginOptions',
            link: '/api-ox/plugin/interfaces/PluginOptions'
          },
          {
            text: 'PluginWithExtension',
            link: '/api-ox/plugin/interfaces/PluginWithExtension'
          },
          {
            text: 'PluginWithoutExtension',
            link: '/api-ox/plugin/interfaces/PluginWithoutExtension'
          },
          {
            text: 'Args',
            link: '/api-ox/plugin/interfaces/Args'
          },
          {
            text: 'ArgSchema',
            link: '/api-ox/plugin/interfaces/ArgSchema'
          },
          {
            text: 'ArgToken',
            link: '/api-ox/plugin/interfaces/ArgToken'
          },
          {
            text: 'Command',
            link: '/api-ox/plugin/interfaces/Command'
          },
          {
            text: 'CommandContext',
            link: '/api-ox/plugin/interfaces/CommandContext'
          },
          {
            text: 'CommandContextExtension',
            link: '/api-ox/plugin/interfaces/CommandContextExtension'
          },
          {
            text: 'GunshiParams',
            link: '/api-ox/plugin/interfaces/GunshiParams'
          }
        ]
      },
      {
        text: 'Type Aliases',
        collapsed: true,
        items: [
          {
            text: 'OnPluginExtension',
            link: '/api-ox/plugin/type-aliases/OnPluginExtension'
          },
          {
            text: 'Plugin',
            link: '/api-ox/plugin/type-aliases/Plugin'
          },
          {
            text: 'PluginExtension',
            link: '/api-ox/plugin/type-aliases/PluginExtension'
          },
          {
            text: 'PluginFunction',
            link: '/api-ox/plugin/type-aliases/PluginFunction'
          },
          {
            text: 'ArgValues',
            link: '/api-ox/plugin/type-aliases/ArgValues'
          },
          {
            text: 'Awaitable',
            link: '/api-ox/plugin/type-aliases/Awaitable'
          },
          {
            text: 'CommandContextCore',
            link: '/api-ox/plugin/type-aliases/CommandContextCore'
          },
          {
            text: 'CommandDecorator',
            link: '/api-ox/plugin/type-aliases/CommandDecorator'
          },
          {
            text: 'CommandExamplesFetcher',
            link: '/api-ox/plugin/type-aliases/CommandExamplesFetcher'
          },
          {
            text: 'CommandRunner',
            link: '/api-ox/plugin/type-aliases/CommandRunner'
          },
          {
            text: 'DefaultGunshiParams',
            link: '/api-ox/plugin/type-aliases/DefaultGunshiParams'
          },
          {
            text: 'ExtendContext',
            link: '/api-ox/plugin/type-aliases/ExtendContext'
          },
          {
            text: 'GunshiParamsConstraint',
            link: '/api-ox/plugin/type-aliases/GunshiParamsConstraint'
          },
          {
            text: 'LazyCommand',
            link: '/api-ox/plugin/type-aliases/LazyCommand'
          },
          {
            text: 'Prettify',
            link: '/api-ox/plugin/type-aliases/Prettify'
          },
          {
            text: 'RendererDecorator',
            link: '/api-ox/plugin/type-aliases/RendererDecorator'
          },
          {
            text: 'ValidationErrorsDecorator',
            link: '/api-ox/plugin/type-aliases/ValidationErrorsDecorator'
          }
        ]
      },
      {
        text: 'Variables',
        collapsed: true,
        items: [
          {
            text: 'ANONYMOUS_COMMAND_NAME',
            link: '/api-ox/plugin/variables/ANONYMOUS_COMMAND_NAME'
          },
          {
            text: 'CLI_OPTIONS_DEFAULT',
            link: '/api-ox/plugin/variables/CLI_OPTIONS_DEFAULT'
          }
        ]
      }
    ]
  },
  {
    text: 'Renderer',
    link: '/api-ox/renderer/',
    collapsed: true,
    items: [
      {
        text: 'Functions',
        collapsed: true,
        items: [
          {
            text: 'renderHeader',
            link: '/api-ox/renderer/functions/renderHeader'
          },
          {
            text: 'renderUsage',
            link: '/api-ox/renderer/functions/renderUsage'
          },
          {
            text: 'renderValidationErrors',
            link: '/api-ox/renderer/functions/renderValidationErrors'
          }
        ]
      }
    ]
  }
]
