.TH "MY\-TOOL" "1" "February 2026"
.SH "NAME"
\fBmy-tool\fR \- A utility for processing data
.SH SYNOPSIS
.P
my\-tool <OPTIONS>
.SH DESCRIPTION
.P
A utility for processing data
.SH OPTIONS

.RS 1
.IP \(bu 2
\fB\-h\fP, \fB\-\-help\fP
.br
Display this help message
.IP \(bu 2
\fB\-v\fP, \fB\-\-version\fP
.br
Display this version
.IP \(bu 2
\fB\-i\fP, \fB\-\-input\fP <input>
.br
Input file path
.IP \(bu 2
\fB\-o\fP, \fB\-\-output\fP <output>
.br
Output file path (defaults to stdout)
.IP \(bu 2
\fB\-f\fP, \fB\-\-format\fP <format>
.br
Output format (json, yaml, xml)
.IP \(bu 2
\fB\-V\fP, \fB\-\-verbose\fP
.br
Enable verbose output

.RE
.SH EXAMPLES
.P
See command \fB\-\-help\fP for examples
.SH AUTHOR
.P
Created by yours
.SH SEE ALSO

.RS 1
.IP \(bu 2
man: \fBman my\-tool\fP
.IP \(bu 2
website: https://my-tools.com/references/cli
.IP \(bu 2
repository: https://github.com/your-username/my-tool

.RE
